

#define RED_LED_EN HAL_GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_SET)
#define RED_LED_DIS HAL_GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_RESET)
#define RED_LED_TOG HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_14)

#define GREEN_LED_EN HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, GPIO_PIN_SET)
#define GREEN_LED_DIS HAL_GPIO_WritePin(GPIOD, GPIO_PIN_12, GPIO_PIN_RESET)
#define GREEN_LED_TOG HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_12)

#define ORANGE_LED_EN HAL_GPIO_WritePin(GPIOD, GPIO_PIN_13, GPIO_PIN_SET)
#define ORANGE_LED_DIS HAL_GPIO_WritePin(GPIOD, GPIO_PIN_13, GPIO_PIN_RESET)
#define ORANGE_LED_TOG HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_13)

#define BLUE_LED_EN HAL_GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_SET)
#define BLUE_LED_DIS HAL_GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_RESET)